spring:
  datasource:
    url: jdbc:h2:file:./data/vne_shop;DB_CLOSE_DELAY=-1;AUTO_SERVER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
    password: ""
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true
      path: /h2-console


server:
  port: 8080

# For local dev logs
logging:
  level:
    org.hibernate.SQL: warn
